theme: jekyll-theme-minimal
permalink: /blog/:year/:month/:day/:title
title: Courtney A. Floyd
description: Academic & Professional Portfolio
logo: <img src="DrCFloyd.github.io/screen-shot-2018-08-07-at-2-06-37-pm.png" alt="Photo of Courtney in sunlit window with short hair"/>
